### ISSUE TITLE
Getting a NullPointerException with customized BeanResolverBuilder

### ISSUE THREAD

**Issue by npgall** [leangen/graphql-spqr#7] opened 2017-07-25 17:33 UTC
Hi,
First of all thanks so much for this impressive library!

I am quite new to GraphQL, but I am hoping to use this library to add GraphQL support to a lot of existing APIs which are currently designed for JSON REST services. The aim is to provide both REST and GraphQL endpoints.

For this to work, I'm hoping to configure GraphQL SPQR library to leverage the existing [jackson-annotations](https://github.com/FasterXML/jackson-annotations) which are already present in the codebase. For the most part this actually works quite well. I have been able to configure the library to read GraphQL query names from `@JsonProperty` annotations, and to ignore properties which are annotated with `@JsonIgnore`. So effectively I've been able to make a bunch of APIs available via GraphQL endpoints without having to modify the codebase at all.

However while it works for the most part, I've hit a problem where the library is throwing an NPE when there's a particular combination of annotated members in a class. It seems to be an edge case where two methods have different return types. One of them should be ignored, but it seems to cause an NPE anyway. I was able to make a small test case below which reproduces the problem.

Is there anything I could do to work around the problem? Or is this a bug which could be fixed?

```java
package io.leangen.graphql;

import com.fasterxml.jackson.annotation.JsonIgnore; // Needs a dependency on jackson-annotations
import com.fasterxml.jackson.annotation.JsonProperty; // Needs a dependency on jackson-annotations
import graphql.schema.GraphQLSchema;
import io.leangen.graphql.metadata.strategy.query.*;
import java.lang.reflect.*;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Predicate;
import org.junit.Test;

public class NPETest {

    /** This test reproduces a NullPointerException when generating the schema using BeanResolverBuilder. */
    @Test
    public void testForNPE() {

        UserService userService = new UserService();

        final ResolverBuilder resolverBuilder = new BeanResolverBuilder(null)
                .withFilters(inclusionFilter)
                .withOperationNameGenerator(jsonAnnotationAwareNameGenerator);

        GraphQLSchema schema = new GraphQLSchemaGenerator()
                .withResolverBuilders(resolverBuilder)
                .withNestedResolverBuilders(resolverBuilder)
                .withOperationsFromSingleton(userService)
                .withDefaults()
                .generate();
    }

    /** An example service we want to expose via GraphQL. */
    public static class UserService {

        public User getUser() {
            return new User();
        }
    }

    /** An example POJO the service returns, which has Jackson annotations we want to leverage for marshalling. */
    public static class User {

        @Deprecated
        @JsonIgnore // This property should be ignored, but its presence seems to cause an NPE anyway.
        public ArrayList<String> getName() { // Note the return type is ArrayList.
            return new ArrayList<>();
        }

        @JsonProperty("name") // The replacement for the method above.
        public List<String> getFullName() { // Note the return type is a List (it differs from above).
            return new ArrayList<>();
        }
    }

    /**
     * An inclusion filter/predicate which indicates that a field or method should be included
     * if it is NOT annotated with @JsonIgnore.
     */
    static final Predicate<Member> inclusionFilter = member ->
                        !((AnnotatedElement)member).isAnnotationPresent(JsonIgnore.class);

    /**
     * An operation name generator which reads the name from a @JsonProperty annotation on a method if present,
     * but otherwise delegates to the superclass which reads the name of the method itself.
     */
    static final OperationNameGenerator jsonAnnotationAwareNameGenerator = new BeanOperationNameGenerator() {

        @Override
        public String generateQueryName(Method queryMethod, AnnotatedType declaringType, Object instance) {
            JsonProperty jsonProperty = queryMethod.getAnnotation(JsonProperty.class);
            return jsonProperty != null ? jsonProperty.value() : super.generateQueryName(queryMethod, declaringType, instance);
        }
    };
}
```

**Comment by kaqqao** [comment] 2017-07-25 19:34
Beautiful bug report! Thanks a bunch for providing an easy way to reproduce!
Also, I really like your use-case! I've been planning for a while now to have something like that out of the box.

I'll investigate what's causing an error ASAP.

**Comment by npgall** [comment] 2017-07-25 20:03
Many thanks. Let me know if you need anything!

**Comment by kaqqao** [comment] 2017-07-25 21:52
Ah, I see what's happening.

1. You registered a customized `BeanResolverBuilder` but also added the default ones via `withDefaults`
2. The custom one correctly discovers only a single method (ignores the one with `@JsonIgnore`), but the default accepts both
3. The query names for both ends up being `name` (one by default, the other because of `@JsonProperty`) so they get merged as 2 resolvers for the same query
4. The merge process attempts to reconcile the return types: `List<String>` and `ArrayList<String>` and comes up with raw `List` (this process is rather primitive and can only deal simple cases... so avoid ever having multiple resolvers for the same query with different returns types)
5. The list mapper tries to figure out the type of the list, and gets `null` for raw `List` (this could likely be done better) and this is where the NPE is coming from

So, to solve your immediate issue, **simply drop the call to `withDefaults()`** 😀
If you ever really need multiple resolvers, make sure their types are the same, to avoid weird cases like this one. At least until I figure out a way to merge the types more intelligently.

I'll still keep this issue open because I could improve the type resolution and list mapping logic, so this will serve as a reminder.

**Comment by npgall** [comment] 2017-07-26 10:20
Thanks so much for your help. I can confirm that worked!
This is an awesome library. Many thanks again!

**Comment by kaqqao** [comment] 2017-07-26 10:32
Glad to help and thanks for the kind words!

**Closed** 2017-08-20 11:35 UTC

**Comment by MFaisalHyder** [comment] 2019-04-17 09:18
Hi, can you tell how you made GraphQL use @JsonProperty instead of declared variable in Java POJO?
I am using graphql-java-tools for auto schemaParsing.

**Comment by kaqqao** [comment] 2019-04-17 09:27
@MFaisalHyder You have something mixed up. graphql-java-tool is a library for schema-first development, SPQR is code-first. There's no logical way (or reason) for using them together.

**Comment by MFaisalHyder** [comment] 2019-04-17 09:39
> @MFaisalHyder You have something mixed up. graphql-java-tools is a library for schema-first development, SPQR is code-first. There's no logical way (or reason) for using them together.

Thanks for clarification, I have started to work on it, and was caught in this problem of fieldName issue. Are there any approaches to tackle this while using gql-j-tools?
