### ISSUE TITLE
Problem on lists

### ISSUE THREAD

**Issue by gfsilva92** [leangen/graphql-spqr#63] opened 2018-02-02 14:53 UTC
Hey,

I have a POJO which has the field:

public List<String> getJurisdiction() {
        return jurisdiction;
    }

In order to use graphql-spqr I put it like this:

@GraphQLQuery(name = "jurisdiction")
    public List<String> getJurisdiction() {
        return jurisdiction;
    }

The problem is that I think the generated schema is with jurisdiction type as string instead of list of strings.

Do you know if I'm doing something wrong?

Thanks.

**Comment by kaqqao** [comment] 2018-02-02 16:46
I'll check it in detail later today, but for the moment, can you try specifying the generic type of the list e.g. `List<String>` and see if there's any difference?

**Comment by kaqqao** [comment] 2018-02-02 16:49
Since SPQR is all about mapping types, having full generic types is very important. Without them, it will treat it as `List<Object>` (like like Java does), and that can have bad side effects. But it still shouldn't treat an entire list like a scalar (you said it was treated as a string)... so I'm not sure what happened there. Will check later, as promised.

**Comment by kaqqao** [comment] 2018-02-02 22:54
Actually, now that I look into this further, this should throw an exception. Unless you explicitly register a permissive type transformer (as described in https://github.com/leangen/graphql-spqr/wiki/Errors#ambiguous-member-type), raw types are treated as errors.

So I really don't understand how you ended up in this situation. Can you share more details? How do you configure the generator? Is the type really just a raw `List`?

**Comment by gfsilva92** [comment] 2018-02-05 11:00
I changed to <List> and it started working. Thanks a lot :)

**Comment by gfsilva92** [comment] 2018-02-05 11:08
It still not working... I will give you details later.

**Comment by kaqqao** [comment] 2018-02-07 22:11
Any updates?

**Comment by gfsilva92** [comment] 2018-02-08 11:06
I'm building a Java API with GraphQL and DGraph as database. I could have it working for now through a schema mutation that says directly that jurisdiction is a list string:

`jurisdiction: [string] .`

I'm using SpringBoot so I configure the schema like this:

```
   @Bean
    GraphQLSchema buildSchema() {
        return new GraphQLSchemaGenerator().withOperationsFromSingletons(query, mutation).generate();
    }
```

The version of SPQR that I'm using is:

```
<dependency>
            <groupId>io.leangen.graphql</groupId>
            <artifactId>spqr</artifactId>
            <version>0.9.5</version>
</dependency>
```

The only thing that I did, that I would expect to work, was to add the GraphQLQuery annotation on the POJO's jurisdiction field, like this:

```
    @GraphQLQuery(name = "jurisdiction")
    public List<String> getJurisdiction() {
        return jurisdiction;
    }
```


Any idea? Sorry for the delay on answer.

**Comment by kaqqao** [comment] 2018-02-08 18:35
All you showed looks perfectly fine... But one thing draws my attention. You said "I could have it working for now through a schema mutation that says directly that jurisdiction is a list string". How did you do that? In SPQR, you never write schema definition language yourself...

Can you show a piece of the classes of the `query` and `mutation` beans you register as singletons? Are they special in any way?

**Comment by gfsilva92** [comment] 2018-02-12 17:43
Sorry for the delay in the answer.

I think the problem is in the database. Because it works if I do an alter operation on the database to specify that the jurisdiction field is a list. I thought it was related with this but probably its not.

How can I see the generated graphql schema?


Query class

```
public class Query extends RootResolver {

    private final static Logger LOGGER = Logger.getLogger(Query.class);

    private final static List<String> RELATIONS = Arrays.asList(BROADER.toString(), NARROWER.toString(),
            SYNONYM.toString(), ANTONYM.toString(), TECHNICAL.toString(), RELATED.toString());
    public static final int DEFAULT_PAGE_SIZE = 10;
    public static final int DEFAULT_PAGE = 0;

    public Query(DatabaseAPI databaseAPI, SearchAPI searchAPI, UtilFunctions utils) {
        super(databaseAPI, searchAPI, utils);
    }

    @GraphQLQuery
    public List<Concept> loadConcepts(@GraphQLArgument(name = "filter") ConceptFilter filter,
                                      @GraphQLEnvironment ResolutionEnvironment resEnv) {
        ...
    }

...
```

Muation class

```
public class Mutation extends RootResolver {

    private final static Logger LOGGER = Logger.getLogger(Mutation.class);

    public Mutation(DatabaseAPI databaseAPI, SearchAPI searchAPI, UtilFunctions utils) {
        super(databaseAPI, searchAPI, utils);
    }

    @GraphQLMutation(name = "createConcept")
    public Concept createConcept(@GraphQLArgument(name = "data") ConceptInput data,
                                 @GraphQLEnvironment ResolutionEnvironment resEnv) {
        ...
    }
```

**Comment by kaqqao** [comment] 2018-02-12 18:02
Wow, wait. I think you're doing something _very_ weird here. It seems you're using graphql-java-tools and GraphQL-SPQR at the same time, which is something you _really_ shouldn't do.

graphql-java-tools is for schema-first development: you write the schema in SDL and wire the resolvers.
GraphQL-SPQR is for code-first development: you write your Java code and SPQR generates the schema.

You really should decide which approach you're going for and remove the other library.

As for printing the schema, you can use `SchemaPrinter#print`, e.g. `new SchemaPrinter().print(graphQLSchema)`. You can also configure the printer in various ways.

**Comment by zephyring** [comment] 2018-02-13 21:53
Hi, just an unrelated question here. I have an int array in my Java object, and during graphql schema generation phase, it's throwing exception like:
io.leangen.geantyref.TypeArgumentNotInBoundException: Given argument [int] for type parameter [E] is not within the bound [class java.lang.Object]

But if I change it to List<Integer>, it works fine. 

Any ideas to support array?

**Comment by kaqqao** [comment] 2018-02-13 22:05
Argh. Sounds like a bug. Could you please post what the class around it looks like? There seems to be some generics involved and the type detection goes awry.
Also, try with `Integer[]` in place of `int[]`.
And please open a new issue for new questions (or if unsure, you can also ask in [Gitter](https://gitter.im/leangen/graphql-spqr?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)), as it very hard to track stuff otherwise.

**Comment by kaqqao** [comment] 2018-02-13 22:05
Btw, array work fine normally... You stumbled onto a bug :(

**Comment by zephyring** [comment] 2018-02-13 22:22
interesting. After I bumped up version from 0.9.5 to 0.9.6, issue is gone. Thanks for your quick reply!

**Comment by gfsilva92** [comment] 2018-02-14 12:41
I don't have graphql-java-tools as a dependency. Why did you say that I'm using it? 

What I use are SPQR and Dgraph. SPQR I use to generate the graphql schema easily with the annotations. Dgraph is my "graph oriented" database.

But as I said, I think the problem is that I was not specifying on the database schema that it was a list. Because now it works :)

**Comment by kaqqao** [comment] 2018-02-14 12:47
@zephyring Ah, yes. 0.9.6 has various fixes in the way both arrays and primitives are handled. Good it hear it's working as intended there.

@gfsilva92 Ok, my bad then. I though you ere using graphql-java-tools because you were mentioning SDL (`jurisdiction: [string]`) and the ` extends RootResolver` bit looked similar to what you do with graphql-java-tools. Anyway, glad to hear you have it figured out.

I'm closing this issue as all concerns seem to have been addressed.

**Closed by kaqqao** 2018-02-14 12:47 UTC
