### ISSUE TITLE
@GraphQLComplexity not calculating when using multiple queries in single request

### ISSUE THREAD

**Issue by danrix89** [leangen/graphql-spqr#330] opened 2019-12-17 19:59 UTC
I am trying to implement complexity using `@GraphQLComplexity`, but I'm running into an issue where if I make a single request with multiple queries and the first query does not use `@GraphQLComplexity` but the second query does, the second query's complexity expression is ignored.

> NOTE: I'm using Kotlin (it shouldn't make a difference though)

Here is what the code looks like:

```kotlin
    @GraphQLQuery
    fun getUsers(): List<User> = userService.getUsers()

    @GraphQLQuery
    @GraphQLComplexity("100")
    fun getProducts(): List<Product> = productService.getProducts()
```

Here is what an example query looks like:

```graphql
query {

  users {
    username
  }

  products {
    name
  }

}
```

Now let's assume the max complexity is set to `5`. That means that the second query of `products` should restrict the request since its complexity score is 100. However, both queries run without restriction.

If I place the `products` query before the `users` query, the request is properly restricted because 100 (taken from `@GraphQLComplexity("100")`) exceeds the max of `5`.

I would assume that no matter the order in which the queries are placed, complexity is always calculated.

Also, (as a side question) is the complexity score cumulative? Meaning, if I had two queries that by themselves don't trip the max complexity threshold but together do, should the request be restricted if both queries are ever together?

Currently I see the only work around as being every query must have use `@GraphQLComplexity` to avoid this case.

Is this a bug or am I not using it correctly?

**Comment by kaqqao** [comment] 2019-12-19 14:03
I think this is a duplicate of https://github.com/leangen/graphql-spqr/issues/313 which is fixed in master but hasn't been released yet. Am working on releasing it soon.

**Comment by danrix89** [comment] 2019-12-19 14:25
Thank you @kaqqao . 

Just curious, will the multiple query calculation be cumulative? For example:

I have two queries in a single request each with a complexity score of 6 (combined would be 12). The max complexity is 11. If I run both queries together in a single request will the complexity threshold be met because the combined score is 12 > 11?

If not, would there be a way to do this? I'm thinking I'd have to create some sort of work around by saving the cumulative score on the thread local MDC when doing each method's calculation and then check against that cumulative score against the max.

**Comment by kaqqao** [comment] 2019-12-19 14:28
The total complexity is always for the entire query, as sent. So multiple top-level fields should in no way be different than any other field selection.

**Comment by kaqqao** [comment] 2020-02-14 19:33
Duplicates #313

**Closed by kaqqao** 2020-02-14 19:33 UTC
