### ISSUE TITLE
Support Publisher<T> for @GraphQLQuery

### ISSUE THREAD

**Issue by oleg-savko** [leangen/graphql-spqr#45] opened 2017-12-06 09:01 UTC
It would be great if in query also we can use reactive streams, that give chance for use graphQL in reactive way (for example, for me in spring 5 webflux).

Is there is some way to do this now? or can u please suggest some ideas how can i achieve my goal?

**Comment by kaqqao** [comment] 2017-12-06 09:42
You can have an asynchronous query by returning a `CompletableFuture`. Spring's `Mono` can easily be turned into a `CompletableFuture`, and a `Flux` can be turned into a `Mono<List<T>>` first (using `collectList`.

You could/should write custom `TypeMapper`s and `OutputConverter`s that deal with `Mono` and `Flux` automatically (SPQR doesn't have these out-of-the-box because it has to stay framework-agnostic), so you don't have to touch your resolver methods. If this is what you're looking for, I can help you write those. Eventually, I'll publish a separate module for Spring-specific stuff, so this could be a nice start.

**Comment by oleg-savko** [comment] 2017-12-06 10:35
Thanks for response. Thats how I do this now)
But there is issue that I cant solve during last week, when I use reactive WebClient (from spring5) first request successfully executed but second or third request pending forever without response even if I use block() method inside GraphQLQuery (for future the same).. 
And its very disappoint  me, because I dont understand why :( 
WebClient work perfect in any other part of program but not under spqr query.  
(When use restTemplate all work without problem, but I very want to use WebClient)

Code example:
`@GraphQLQuery(name = "signin")
  fun signin(@GraphQLArgument(name = "auth") authRequest: AuthRequest): AuthResponse {
    return client.auth(authRequest).block()
  }`

`override fun auth(authRequest: AuthGraph.AuthRequest): Mono<AuthGraph.AuthResponse> {
    return client
        .post()
        .uri("/auth/token")
        .syncBody(authRequest)
        .retrieve()
        .bodyToMono(String::class.java)
        .map { AuthGraph.AuthResponse(it) }
  }`

This is corresponding log:
`13:21:24.167[DEBUG][][reactor-http-nio-3]o.s.w.r.f.client                         : onSubscribe(FluxMap.MapSubscriber)
13:21:24.167[DEBUG][][reactor-http-nio-3]o.s.w.r.f.client                         : onSubscribe(FluxMap.MapSubscriber)
13:21:24.170[DEBUG][][reactor-http-nio-3]o.s.w.r.f.client                         : request(unbounded)
13:21:24.170[DEBUG][][reactor-http-nio-3]o.s.w.r.f.client                         : request(unbounded)
13:21:24.203[DEBUG][][reactor-http-nio-1]o.s.w.r.f.client                         : onNext(ReactorClientHttpResponse{request=[POST /es-solva-auth-server/auth/token],status=200})
13:21:24.203[DEBUG][][reactor-http-nio-1]o.s.w.r.f.client                         : onNext(ReactorClientHttpResponse{request=[POST /es-solva-auth-server/auth/token],status=200})
13:21:24.204[DEBUG][][reactor-http-nio-1]o.s.w.r.f.client                         : onComplete()
13:21:24.204[DEBUG][][reactor-http-nio-1]o.s.w.r.f.client                         : onComplete()
13:21:24.205[DEBUG][][reactor-http-nio-1]o.s.w.r.f.client                         : cancel()
13:21:24.205[DEBUG][][reactor-http-nio-1]o.s.w.r.f.client                         : cancel()
13:21:25.573[DEBUG][][reactor-http-nio-3]o.s.w.r.f.client                         : onSubscribe(FluxMap.MapSubscriber)
13:21:25.573[DEBUG][][reactor-http-nio-3]o.s.w.r.f.client                         : onSubscribe(FluxMap.MapSubscriber)
13:21:25.573[DEBUG][][reactor-http-nio-3]o.s.w.r.f.client                         : request(unbounded)
13:21:25.573[DEBUG][][reactor-http-nio-3]o.s.w.r.f.client                         : request(unbounded)`


When use @GraphQLSuscription its not occurs and work fine.

Can u suggest what can go wrong, and why it happens?
Any ideas would be very appreciate.

**Comment by kaqqao** [comment] 2017-12-06 12:30
Since this is a problem during execution, there's a high probability it isn't actually a problem with SPQR.
Since it's a lot of effort to replicate your setup, could you try creating a minimal schema using graphql-java directly that tries to reproduce the same error?
Alternatively, if you find it easier, could you create a minimal example of the problem with SPQR, and I'll analyze if it's down to graphql-java or not?

**Comment by oleg-savko** [comment] 2017-12-06 13:12
Yes, ofcourse. 
This is example https://github.com/oleg-savko/graphql-spqr-webflux .
You can check it via http://localhost:8080/graphiql.html?query=%7B%0A%20%20test%20%7B%0A%20%20%20%20response%0A%20%20%7D%0A%7D

On third request it pending.

**Comment by kaqqao** [comment] 2017-12-06 23:41
Wow... I have no clue what's going on, but I managed to get the same behavior even without any GraphQL involved:

```java
  TestGraph service = new TestGraph(WebClient.builder().build());

  @Bean
  RouterFunction router(GraphQL graphQL) {
    return resources("/**", new ClassPathResource("static/"))
        .and(route(GET("/graphql"),
                    r -> get()
            ));
  }

  private Mono<ServerResponse> get() {
    TestResponse resp = service.test();
    return ServerResponse.ok().body(BodyInserters.fromObject(resp.getResponse()));
  }
```

I works the first few times (sometimes 2 and sometimes 3 or 4) and then just hangs forever.

At this point, I'd post this example (without GraphQL) to StackOverflow and hope someone will know if there's something wrong in the code or it's a bug in Spring.

**Comment by kaqqao** [comment] 2017-12-07 01:10
Some more observations:
If `TestGraph#test` returns a `Mono` or a `CompletableFuture`, and no blocking methods are ever called, the simple case (no GraphQL) works fine. If any blocking call is involved (e.g. `Mono#block` or `CompletableFuture#join`) it stops working.
If I run the entire `TestGraph#test` in an `Executor` other than the default, it also seems to work even if blocking.
With GraphQL, I never managed to get it to work...

**Comment by kaqqao** [comment] 2017-12-07 01:37
If I rebuild the same schema using graphql-java directly:

```java
  @Bean
  GraphQL graphQL(TestGraph testGraph) {
    GraphQLSchema schema = GraphQLSchema.newSchema()
            .query(GraphQLObjectType.newObject()
                    .name("ROOT")
                    .field(GraphQLFieldDefinition.newFieldDefinition()
                            .name("test")
                            .type(GraphQLObjectType.newObject()
                                    .name("TestResponse")
                                    .field(GraphQLFieldDefinition.newFieldDefinition()
                                            .name("response")
                                            .type(Scalars.GraphQLString)
                                            .build())
                                    .build())
                            .dataFetcher(e -> testGraph.test())
                            .build())
                    .build())
            .build();
    return GraphQL.newGraphQL(schema).build();
  }
```

I get the exact same bizarre behavior :(
I suggest you also post a question there with that example, as I honestly have no clue what else to try...

**Comment by oleg-savko** [comment] 2017-12-07 08:30
The same for me.
Can u share posted question links? Please)

**Comment by kaqqao** [comment] 2017-12-07 15:18
OK, I finally managed to wrap my mind around it.
Here's what's going on:
* you mustn't ever block the main thread, because in that case the thread that's supposed to complete the promise is also waiting for its completion, thus grinding to a halt (that's why the pure Spring example worked when the blocking fetch was executed in a new thread but not otherwise)
* this leaves the options of executing the entire graphql-java call inside a different thread
* or, much better yet, use `graphQL.executeAsync` instead of `graphQL.execute` and never have a blocking call in the first place. This was the real error all along...

To conclude, your resolve should look like this:

```java
  @GraphQLQuery(name = "test")
  public CompletableFuture<TestResponse> test() {
    return client.get()
        .uri("https://google.com")
        .retrieve()
        .bodyToMono(String.class)
        .map(TestResponse::new)
        .toFuture();
  }
```

and your controller logic like this:

```java
@Bean
  RouterFunction router(GraphQL graphQL) {
    return resources("/**", new ClassPathResource("static/"))
        .and(route(POST("/graphql"),
            r -> r.bodyToMono(GraphQLRequest.class)
                .flatMap(q -> {
                  ExecutionInput input = ExecutionInput.newExecutionInput().query(q.query).build();
                  CompletableFuture<ExecutionResult> result = graphQL.executeAsync(input); //THIS IS IMPORTANT
                  return Mono.fromFuture(result).flatMap(s -> ServerResponse.ok().body(BodyInserters.fromObject(s)));
                })));
  }
```

With this, it all works like it should :)

And it brings us back to my first message: you can make a nice `Mapper/Converter` that deals with `Mono/Flux` directly, so you don't need to call `toFuture` yourself.
I'll do this myself soon enough as a start of the Spring-specific support.

**Comment by kaqqao** [comment] 2017-12-08 09:15
Can you verify if this works and if I can close the issue?

**Comment by oleg-savko** [comment] 2017-12-08 09:33
Thanks for you explanation!
Its really great, if at first time, I cant even imagine, what going wrong, now the main concept clear.
Need something read about Netty event loop to understand why it not release worker/handler when operation done to not produce this mistake late.

Its work like u describe, but now I found one more problem.

Seems like it steel not work with batching, because its required blocking api 

private void validateBatching(String executableSignature, AnnotatedType returnType, Set<OperationArgument> contextArguments) {

        if (contextArguments.isEmpty() || !Stream.concat(contextArguments.stream().map(arg -> arg.getJavaType().getType()), Stream.of(returnType.getType()))
                .allMatch(type -> GenericTypeReflector.isSuperType(List.class, type))) {

            throw new IllegalArgumentException("Resolver method " + executableSignature
                    + " is marked as batched but doesn't return a list or its context argument is not a list");
        }
    }


Can u suggest something how it can be solved?

**Comment by kaqqao** [comment] 2017-12-08 10:06
Methods with `@Batched` *must* return a `List` (should be `Iterable` but it's `List` at the moment). They receive a `List` of context objects (as `@GraphQLContext`) and must return a list of results in turn. See [`BatchingTest`](https://github.com/leangen/graphql-spqr/blob/master/src/test/java/io/leangen/graphql/BatchingTest.java) for an example.
I *think* `BatchedExecutionStrategy` is compatible with the async execution, but if not, you should look into [dataloader](https://github.com/graphql-java/java-dataloader) instead.
At any rate, the intricacies of async execution are really down to graphql-java and not SPQR.

**Closed by kaqqao** 2017-12-08 10:06 UTC
