### ISSUE TITLE
Relay pagination and sub-query exception

### ISSUE THREAD

**Issue by depauwjimmy** [leangen/graphql-spqr#13] opened 2017-08-09 15:23 UTC
Hello again,

I am back again with the relay pagination.
While waiting for the 0.9.4 which will have the duplicate parameter problem fixed, i am using `@GraphQLEnvironment ResolutionEnvironment` to recover the values.
It works fine.

Now i want to paginate sub-queries and i have a problem.

The signature is now : 

`public Page<Vote> getUserVotes(@GraphQLContext User user, @GraphQLEnvironment ResolutionEnvironment env)`

Below the users query is working fine with pagination.
userVotes is another paginated query, as long as i don't specify any parameters (like first) it works fine and it uses my default value for first.

```
{
	users(first:50) {
		pageInfo {
			startCursor
			endCursor
			hasNextPage
		}
		edges {
			node {
				id
				firstName
				lastName
				displayName
				userVotes {
					pageInfo {
						startCursor
						endCursor
						hasNextPage
					}
					edges {
						node {
							id
						}
					}
				}
			}
		}
	}
}
```

But if i do `userVotes(first:50) {` i receive the following exception.
`Caused by: graphql.GraphQLException: Resolver for operation userVotes accepting arguments: [arg0, before, after, first, last] not implemented`

So apparently it cannot find my method signature because it has something else then a ResolutionEnvironment.

Maybe i am doing something really wrong here :)
Thanks in advance for your insight.

**Comment by kaqqao** [comment] 2017-08-10 14:05
I don't think you're doing anything wrong... and I have a theory what is going wrong. I'll get it fixed today and released in 0.9.4 (probably also today).
But... there is one curious thing here, it seems like you have more than one method connected to the `userVotes ` query. Is it by design or by accident?
Asking because when only a single method is found, the check that's failing for you is skipped.

**Comment by depauwjimmy** [comment] 2017-08-10 14:22
That is really curious indeed because as far as i can see, i only have one method linked to userVotes query.
Well i have 2 occurrences of `@GraphQLQuery(name = "userVotes")` in my code, one is on the user model : 

```
public class User extends DomainAbstract {
    ...
    @GraphQLQuery(name = "userVotes")
    private List<Vote> votes;
    ...
}
```

The other one is on the method (the one i posted above) and nowhere else.

```
@GraphQLQuery(name = "userVotes")
    public Page<Vote> getUserVotes(@GraphQLContext User user, @GraphQLEnvironment ResolutionEnvironment env) {
...
}
```

This is the proper way to do it right?
What is certain is that for all Operations Singletons registered on the Schema, there is only one method for userVotes but maybe you can tell me how i can verify that at runtime.

**Comment by depauwjimmy** [comment] 2017-08-11 09:01
Here is the result of my introspection query if it may help.

[introspection.json.zip](https://github.com/leangen/graphql-spqr/files/1217354/introspection.json.zip)

**Comment by kaqqao** [comment] 2017-08-24 17:44
@depauwjimmy Just to give you an update. The issue you're facing is tricky to fix as it hits a few weak spots of the current implementation at the same time. I'm working on it actively though, and will have it done soon, at least to the level that unblocks you. #15 is just another aspect of this same problem, so I'll close both issues at the same time.

**Comment by depauwjimmy** [comment] 2017-08-25 07:18
Thanks for the feedback ;-)

**Comment by kaqqao** [comment] 2017-11-16 01:05
Finally dealt with this one in https://github.com/leangen/graphql-spqr/commit/a7b0c03bef329a6bb242787cd8178878874c0179 so the fix is now in master.

@depauwjimmy While there are still some edge cases that I think are impossible to cleanly deal with, all common use-cases, yours included, should now work as expected. Please give it a go when you can.
I'll release this as a part of v0.9.4, likely tomorrow.

**Closed by kaqqao** 2017-11-16 01:05 UTC

**Comment by kaqqao** [comment] 2017-11-16 01:10
Oh, forgot to mention, the paging arguments are no longer added automatically, so the ones you specify as method parameters are the only ones that get mapped. This should get rid of the duplicate arguments issue, and avoid a lot of confusion.
As a result, injecting `ResolutionEnvironment` is no longer necessary.

**Comment by depauwjimmy** [comment] 2017-11-16 07:55
Thanks a lot!
